- Esc + m: convert code cell to markdown cell
- Esc + y: convert markdown cell to code cell
- shift + enter: to execute cell

# Title
## Heading 2
### Heading 3
#### Heading 4
##### Heading 5

### Python Libraries
- NumPy
- Pandas
- Matplotlib
- Seaborn
- Scikit Learn

### NumPy
- Numerical Python
- Numpy library is written for scientific computing and data analysis
- Numpy can do mathmetical calculations at faster and easier way 
- https://numpy.org/

In [1]:
### Installation
# pip install numpy 

#  or

# conda install numpy

In [3]:
### Importing numpy
import numpy as np

In [4]:
# To check Version
np.__version__

'1.16.4'

In [7]:
# to check numpy methods
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

#### Create array
- we can create array in different ways
    - List
    - Tuple
    - dict

In [8]:
# 1-Dimensional array

n1 = np.array([0,1,2,3,4])
n1

array([0, 1, 2, 3, 4])

In [12]:
print(type(n1))
print(n1.ndim) # to check dimesion
print(n1.itemsize) # how much memory used by each element in bytes
print(n1.dtype)

<class 'numpy.ndarray'>
1
4
int32


In [13]:
# 2-Dimensional array
# np.array( [ [ row1 ], [ row2 ],.... ] )

n2 = np.array([ [1,2,3,4], [5,6,7,8] ])
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
print(n2.ndim) 
print(n2.itemsize) 

2
4


In [17]:
# 3-Dimensional or Multi dimensional array

n3 = np.array( [ [ [10,20],[30,40] ] ] )
n3

array([[[10, 20],
        [30, 40]]])

In [18]:
print(n3.ndim) 

3


In [20]:
# np.array( [ [ [],[] ], [ [],[] ] ] )
n33 = np.array([ [ [1,2,3],[4,5,6] ], [ [10,20,30],[40,50,60] ] ])
n33

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [21]:
n33.ndim

3

**Why numpy when we have List ?**

In [22]:
list1 = [1,2,3]
list1 + 10

TypeError: can only concatenate list (not "int") to list

In [23]:
npArray = np.array([1,2,3])
npArray + 10

array([11, 12, 13])

#### Advanyages of numpy
- NumPy is much faster than standard python ways to do computations
- NumPy arrays are more compact than list. It takes lesser storage space comparing to list

### NumPy methods
- np.arange()
- np.linspace()
- np.ones()
- np.zeros()
- np.reshape()
- Statistical methods

In [25]:
# for loop Vs np.arange()

for i in range(0,11):
    print(i, end='\t')

0	1	2	3	4	5	6	7	8	9	10	

In [26]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.arange(0,101, 5) # every 5th value
# np.arange(start, stop, skip/step)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [29]:
## np.linspace()

np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [30]:
len(np.linspace(0,10,20))

20

In [31]:
1.05263158 - 0.52631579

0.52631579

In [32]:
6.31578947 - 5.78947368

0.52631579

In [33]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [34]:
np.linspace(0,10,20, retstep=True)

(array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
         2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
         5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
         7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]),
 0.5263157894736842)

In [36]:
# np.ones()
np.ones(5)

array([1., 1., 1., 1., 1.])

In [37]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [38]:
# np.zeros()
## similar to np.ones()

In [39]:
# Accesing elements from array
a1 = np.arange(10,21)
a1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [40]:
a1[0]

10

In [41]:
a1[3]

13

In [42]:
a1[-1]# -ve indexing

20

In [43]:
a1[:3]

array([10, 11, 12])

In [44]:
a1[-3:]

array([18, 19, 20])

In [45]:
a1[::-1]# reverse array

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [46]:
a1[[3,6]] # multiple values

array([13, 16])

**np.reshape()**
- Giving a new shape to an array
- Product of rows & columns in new array should be equal to total no elements

In [47]:
b1 = np.array([ [1,2,3,4,5], [11,12,13,14,15] ])
b1 # Total 10 elements 

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [48]:
b1.shape # no. of rows and columns

(2, 5)

In [49]:
## 2 rows and 5 columns
# 2 * 5 = 10
# 5 * 2 = 10
# 1 * 10 = 10
# 10 * 1 = 10

In [52]:
b11 = b1.reshape(5,2)

In [53]:
b11

array([[ 1,  2],
       [ 3,  4],
       [ 5, 11],
       [12, 13],
       [14, 15]])

In [51]:
b1.reshape(5,2).shape

(5, 2)

#### Statistaical operations

In [54]:
b1

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [58]:
print(np.max(b1))# maximum value
print(np.min(b1))# minimum value
print(np.argmax(b1))# index of maximum value
print(np.argmin(b1))# index of minimum value

15
1
9
0


In [62]:
print(np.mean(b1))
print(np.median(b1))
print(np.var(b1))# variance
print(np.std(b1))# standard deviation

8.0
8.0
27.0
5.196152422706632


In [66]:
print(np.log(10))
print(np.log10(10))
print(np.log2(10))

print(np.exp(10))

2.302585092994046
1.0
3.321928094887362
22026.465794806718


In [68]:
print(np.sin(3.14 / 6))
print(np.cos(3.14 / 3))

0.4997701026431024
0.5004596890082058
